.PHONY: clean All

All:
	@echo "----------Building project:[ Thompson_CS3305_Lab3 - Debug ]----------"
	@cd "Thompson_CS3305_Lab3" && "$(MAKE)" -f  "Thompson_CS3305_Lab3.mk"
clean:
	@echo "----------Cleaning project:[ Thompson_CS3305_Lab3 - Debug ]----------"
	@cd "Thompson_CS3305_Lab3" && "$(MAKE)" -f  "Thompson_CS3305_Lab3.mk" clean
