.PHONY: clean All

All:
	@echo "----------Building project:[ Thompson_CS3305_Lab11 - Debug ]----------"
	@cd "Thompson_CS3305_Lab11" && "$(MAKE)" -f  "Thompson_CS3305_Lab11.mk"
clean:
	@echo "----------Cleaning project:[ Thompson_CS3305_Lab11 - Debug ]----------"
	@cd "Thompson_CS3305_Lab11" && "$(MAKE)" -f  "Thompson_CS3305_Lab11.mk" clean
