.PHONY: clean All

All:
	@echo "----------Building project:[ Thompson_CS3305_Assignment4 - Debug ]----------"
	@cd "Thompson_CS3305_Assignment4" && "$(MAKE)" -f  "Thompson_CS3305_Assignment4.mk"
clean:
	@echo "----------Cleaning project:[ Thompson_CS3305_Assignment4 - Debug ]----------"
	@cd "Thompson_CS3305_Assignment4" && "$(MAKE)" -f  "Thompson_CS3305_Assignment4.mk" clean
