.PHONY: clean All

All:
	@echo "----------Building project:[ Lab01 - Debug ]----------"
	@cd "Lab01" && "$(MAKE)" -f  "Lab01.mk"
clean:
	@echo "----------Cleaning project:[ Lab01 - Debug ]----------"
	@cd "Lab01" && "$(MAKE)" -f  "Lab01.mk" clean
