.PHONY: clean All

All:
	@echo "----------Building project:[ CodeStuff01 - Debug ]----------"
	@cd "CodeStuff01" && "$(MAKE)" -f  "CodeStuff01.mk"
clean:
	@echo "----------Cleaning project:[ CodeStuff01 - Debug ]----------"
	@cd "CodeStuff01" && "$(MAKE)" -f  "CodeStuff01.mk" clean
